# Use NGINX Alpine image for a smaller footprint
FROM nginx:alpine

# Label for maintainer
LABEL maintainer="your_email@example.com"

# Copy static files
COPY ./backend/static /usr/share/nginx/html/static

# Copy the index.html to the root of Nginx's serve directory
COPY ./backend/templates/index.html /usr/share/nginx/html/

# Apply Nginx configuration
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for the web server
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
